/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MeusPedidosRouteImport } from './routes/meus-pedidos'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PedidoTokenRouteImport } from './routes/pedido.$token'

const MeusPedidosRoute = MeusPedidosRouteImport.update({
  id: '/meus-pedidos',
  path: '/meus-pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoTokenRoute = PedidoTokenRouteImport.update({
  id: '/pedido/$token',
  path: '/pedido/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/meus-pedidos': typeof MeusPedidosRoute
  '/pedido/$token': typeof PedidoTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/meus-pedidos': typeof MeusPedidosRoute
  '/pedido/$token': typeof PedidoTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/meus-pedidos': typeof MeusPedidosRoute
  '/pedido/$token': typeof PedidoTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/meus-pedidos' | '/pedido/$token'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/meus-pedidos' | '/pedido/$token'
  id: '__root__' | '/' | '/admin' | '/meus-pedidos' | '/pedido/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  MeusPedidosRoute: typeof MeusPedidosRoute
  PedidoTokenRoute: typeof PedidoTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/meus-pedidos': {
      id: '/meus-pedidos'
      path: '/meus-pedidos'
      fullPath: '/meus-pedidos'
      preLoaderRoute: typeof MeusPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$token': {
      id: '/pedido/$token'
      path: '/pedido/$token'
      fullPath: '/pedido/$token'
      preLoaderRoute: typeof PedidoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  MeusPedidosRoute: MeusPedidosRoute,
  PedidoTokenRoute: PedidoTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
